theme: jekyll-theme-cayman
title: The Invisible Botmobile
description: ECE 3400 Team 3 - Sid Vadduri, Jay Chand, Jessica Lee, and Emily Wang
show_downloads: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
